source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'OverlayView_Example', :exclusive => true do
  pod "OverlayView", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "OverlayView", :path => "../"

  
end
